services:
  db:
    image: postgres:16-alpine
    container_name: aspg-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - aspg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: aspg-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_DISABLE_POSTFIX: "true"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - aspg-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
    # 🆕 Backend API (NOVO)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aspg-backend
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - aspg-network

  # 🆕 Frontend (NOVO)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aspg-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - aspg-network

volumes:
  pg_data:
  pgadmin_data:

networks:
  aspg-network:
    driver: bridge