services:
  db:
    image: postgres:16-alpine
    container_name: aspg-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - aspg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: aspg-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_DISABLE_POSTFIX: "true"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - aspg-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data:

networks:
  aspg-network:
    driver: bridge